<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
$username = $block->getUsername();
$mobile = '';
$isMobileLogin = true;
if ($username) {
    if (substr($username, 0, 1) == '+') {
        $isMobileLogin = true;
        $mobile = $username;
        $username = '';
    }
}

$availableSocials = $this->getLayout()->createBlock('\Mageplaza\SocialLogin\Block\Popup\social')->getAvailableSocials();
 
?>

<div class="block block-customer-login" id="customer-auth-page">
    <!--    <div class="block-title">-->
    <!--        <strong id="block-customer-login-heading" role="heading" aria-level="2">-->
    <!--            -->
    <?php //= $block->escapeHtml(__('Registered Customers')) ?>
    <!--        </strong>-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="auth-text">
                <!-- <img src="/media/mgs/supro/family-login.png"> -->
                <h2 class="title"><span>
                        <?php echo __('Signin to Baytalebaa') ?>
                    </span>
                    <p class="sub-title">
                    <?php echo __('Sign-in to your account') ?>
                     </p>
                </h2>

            </div>
            <div class='auth-form'>
                <div class="block-content" aria-labelledby="block-customer-login-heading">
                    <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                        data-test_login_action="<?php echo $block->getUrl('vsms/login/loginPost') ?>" method="post"
                        id="login-form">
                        <?= $block->getBlockHtml('formkey') ?>
                        <fieldset class="fieldset login">
                            <!--                    <div class="field note">-->
                            <?php //= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?><!--</div>-->

                            <div class="field email required">
                                <label class="label" for="email">
                                   
                                    <!-- <a class="link sms-login-field-ctrl selected<?php if ($isMobileLogin)
                                        echo " selected" ?>"
                                            href="#<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_MOBILE; ?>"><span
                                            class="link">
                                            <?= $block->escapeHtml(__('Mobile')) ?>
                                        </span></a> -->
                                </label>
                                <div id="by_mobile" class="control sms-login-field" <?php if (!$isMobileLogin)
                                    echo ' style="display: none;"' ?>>
                                        
                                        <label for="login[mobile]" class="label"><span><?=__("Mobile")?></span></label>

                                        <input name="login[mobile]" style="margin-top:5px !important" value="<?= $block->escapeHtml($mobile) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off" <?php endif; ?>
                                        id="mobile-number-input" type="text" class="input"
                                        placeholder="<?php echo __("Enter Phone Number") ?>"
                                        autofocus
                                        title="<?= $block->escapeHtml(__('Mobile')) ?>">
                                    <input type="hidden" name="mobilenumber" id="mobile-number" />
                                    <input type="hidden" name="login_type" id="login_type"
                                        value="<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_MOBILE; ?>" />
                                </div>
                                <div id="by_email" class="control sms-login-field" <?php if ($isMobileLogin)
                                    echo ' style="display: none;"' ?>>
                                        <label for="Email" class="label"><span><?=__("Email")?></span></label>
                                        <input name="login[username]" style="margin-top:5px;" value="<?= $block->escapeHtml($username) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off" <?php endif; ?>
                                        id="email" type="email" class="input"
                                        title="<?= $block->escapeHtml(__('Email')) ?>"
                                        placeholder="<?php echo __("Enter Email Address"); ?>"
                                        data-validate="{required:true, 'validate-email':true}">
                                </div>
                            </div>

                            <div class="field password required" id="magento-password-login" <?php if ($isMobileLogin)
                                    echo ' style="display: none;"' ?>>
                                <div class="form-group">
                                    <label for="pass" class="label"><span>
                                            <?= $block->escapeHtml(__('Password')) ?>
                                        </span></label>
                                    <div class="control password-control">
                                        <input name="login[password]" type="password" 
                                        placeholder="<?php echo __("Enter Password"); ?>"
                                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off" <?php endif; ?>
                                            class="input" id="pass" title="<?= $block->escapeHtml(__('Password')) ?>"
                                            data-validate="{required:true}">
                                            <span class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                    </div>
                                    <a class="action remind "
                                        href="<?php /* @escapeNotVerified */echo $block->getForgotPasswordUrl() ?>"><span
                                            class="link">
                                            <?php /* @escapeNotVerified */echo __('Forgot your password ?') ?>
                                        </span></a>
                                </div>
                            </div>
                            
                            <?= $block->getChildHtml('form_additional_info') ?>
                            <div class="actions-toolbar actions-toolbar-login" <?php if ($isMobileLogin)
                                    echo ' style="display: none;"' ?>>
                                <div class="primary"><button type="submit" class="action login button-primary button-medium"
                                        name="send" id="send2"><span>
                                            <?= $block->escapeHtml(__('Sign In')) ?>
                                        </span></button></div>

                            </div>

                            <div class="actions-toolbar actions-toolbar-otp" <?php if (!$isMobileLogin)
                                    echo ' style="display: none;"' ?>>
                                <div class="primary"><button type="submit" class="action login button-primary button-medium"
                                        name="send" id="send2"><span>
                                            <?= $block->escapeHtml(__('Send Otp')) ?>
                                        </span></button></div>
                            </div>
                            <div>
                                <h5 class="title disable">
                                    <?php echo __("Don't have an account?") ?> <a
                                    class="link"
                                        href="<?= $this->getUrl('customer/account/create'); ?>">
                                        <?= __('Signup') ?>
                                    </a>
                                </h5>
                            </div>
                        </fieldset>
                    </form>
                    <hr/>

                    <?php if (sizeof($availableSocials)): ?>
                   
                    <div class="block social-login-authentication-channel account-social-login">
                        <div class="block-content">
                            <?php foreach ($availableSocials as $key => $social): ?>
                                <div class="actions-toolbar social-btn social-btn-actions-toolbar <?= $key ?>-login">
                                    <a class="button-secondary button-medium btn btn-block btn-social btn-<?= $this->getLayout()->createBlock('\Mageplaza\SocialLogin\Block\Popup\social')->getBtnKey($key) ?>"
                                    data-mage-init='{"socialProvider": {"url": "<?= $social['login_url'] ?>", "label": "<?= __('Login By %1', $social['label']) ?>"}}'>
                                        <span class="fa fa-<?= $this->getLayout()->createBlock('\Mageplaza\SocialLogin\Block\Popup\social')->getBtnKey($key) ?>"></span>
                                        <?= __('Continue With '.$social['label']) ?>
                                    </a>
                                </div>
                            <?php endforeach; ?>

                            <div id="social-btn-email" class="actions-toolbar social-btn social-btn-actions-toolbar <?= $key ?>-login">
                                <a class="button-secondary button-medium btn-social sms-login-field-ctrl <?php if (!$isMobileLogin) echo " selected" ?>"
                                    href="#<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_EMAIL; ?>">
                                    <i class="fa fa-regular fa-envelope"></i>
                                            <?= __('Continue With Email') ?>
                                </a>
                            </div>
                            <div id="social-btn-mobile" class="actions-toolbar social-btn  social-btn-actions-toolbar <?= $key ?>-login" style="display:none;">
                                <a class="button-secondary button-medium btn-social sms-login-field-ctrl <?php if ($isMobileLogin) echo " selected" ?>"
                                    href="#<?php echo \Vnecoms\Sms\Helper\Data::LOGIN_TYPE_MOBILE; ?>">
                                    <i class="fa fa-regular fa-envelope"></i>
                                            <?= __('Continue With Mobile') ?>
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>


                </div>
            </div>
        </div>
    </div>
    <?php
    /** @var \Vnecoms\Sms\Helper\Data $smsHelper*/
    $smsHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Vnecoms\Sms\Helper\Data');
    $mobile = \Magento\Framework\App\ObjectManager::getInstance()->get('Vnecoms\Sms\Model\Mobile');

    ?>

    <script>


    </script>
    <script type="text/javascript">
        require([
            'jquery',
            'jquery/intltellinput',
            'Vnecoms_Sms/js/utils',
            'smsLogin',
            'domReady!'
        ], function ($) {
            $(document).ready(function(){
                // Show the appropriate link based on the initial condition
                if ($('.login-buttons .link.selected').hasClass('sms-login-field-ctrl')) {
                    $('.login-buttons .link.sms-login-field-ctrl').show();
                } else {
                    $('.login-buttons .link.sms-login-field-ctrl.selected').show();
                }

                $('.login-buttons .link').click(function(e){
                    e.preventDefault();
                    // Toggle the selected class and hide/show links based on the condition
                    $('.login-buttons .link').removeClass('selected').hide();
                    $(this).addClass('selected').show();
                });
            });
            $('.block-customer-login').smsLogin({
                login_type_config: '<?php echo $smsHelper->getConfigTypeLogin(); ?>',
                initialCountry: '<?php echo strtolower($smsHelper->getInitialCountry()); ?>',
                allowDropdown: <?php echo strtolower($smsHelper->getAllowCountryDropdown()); ?>,
                onlyCountries: <?php echo $smsHelper->isAllowedAllCountries() ? '[]' : json_encode(explode(",", $smsHelper->getAllowedCountries())); ?>,
                preferredCountries: <?php echo json_encode(explode(',', $smsHelper->getPreferredCountries())); ?>,
                geoIpUrl: '<?php echo $smsHelper->getGeoIpDatabase() ? $this->getUrl('vsms/geoip') : 'https://ipinfo.io'; ?>'
            });
        });
    </script>
    <?php if ($smsHelper->isEnabledOtpLogin() || $smsHelper->isEnabled2FALogin()): ?>
        <script type="text/x-magento-init">
            {
                "#login-form": {
                    "Vnecoms_Sms/js/validate-customer": {
                        "sendOtpURL":"<?php echo $block->getUrl('vsms/otp_login/send') ?>",
                        "verifyOtpURL":"<?php echo $block->getUrl('vsms/otp_login/verify') ?>",
                        "login_type_config": "<?php echo $smsHelper->getConfigTypeLogin(); ?>"
                    }
                }
            }
        </script>
        <div class="ves-loadingbox" id="ves-loadingbox">
            <div class="ves-overlay">
                
            </div>
            <div class="loading-img"></div>
        </div>
        <div class="sms-otp-dialog" id="sms-otp-dialog">
            <div class="sms-otp-step-1">
                <p>
                    <?php echo __("This extra step shows it’s really you trying to sign in. Click to the button below to send an OTP to your phone number") ?>
                    
                    <span class="sms-otp-mobile"></span>
                </p>
                <button class="action button-primary button-medium send-otp-btn" id="send-otp-btn"><span>
                        <?php echo __("Get OTP") ?>
                    </span></button>
            </div>
            <div class="sms-otp-step-2">
                <p>
                    <?php echo __("A text message with a %1-digit verification code has been sent to", $block->getCustomer()) ?>
                    <span id="sms-otp-dialog-mobile" class="sms-otp-mobile"></span>
                </p>
                <!-- <input type="text" name="sms_otp_code" autocomplete="one-time-code" inputmode="numeric" maxlength="4" pattern="\d{4}" id="sms-otp-input" value="" class="input required-entry"/>
                    placeholder="<?php echo __("Your OTP") ?>"  -->
                    <div class="otp-inputfield" id="otp-inputfield">
                        <input type="number" maxlength="1" placeholder="1" class="otp-input" id="first-input" />
                        <input type="number" maxlength="1" placeholder="2" class="otp-input" />
                        <input type="number" maxlength="1" placeholder="3" class="otp-input" />
                        <input type="number" maxlength="1" placeholder="4" class="otp-input" />
                    </div>

                <button class="action button-primary button-medium send-otp-btn" id="verify-otp-btn"><span>
                        <?php echo __("Verify") ?>
                    </span></button>
                <a href="#" class="resend-otp-btn link" id="resend-otp-btn"
                    data-time="<?php echo $smsHelper->getOtpResendPeriodTime() ?>">
                    <?php echo __("Resend after %1 seconds", $smsHelper->getOtpResendPeriodTime()) ?>
                </a>
            </div>
        </div>
    <?php endif; ?>
</div>

<script>
    // custom code for otp style animation
    const input = document.querySelectorAll(".otp-input");
    const inputField = document.querySelector(".otp-inputfield");
    const submitButton = document.getElementById("verify-otp-btn");
    let inputCount = 0,
    finalInput = "";

    // Function to check if all input fields are filled
    const allInputsFilled = () => {
    return Array.from(input).every((element) => element.value.length === 1);
    };

    //Update input
    const updateInputConfig = (element, disabledStatus) => {
    element.disabled = disabledStatus;
    if (!disabledStatus) {
        element.focus();
    } else {
        element.blur();
    }
    };

    //auto 
    function focusOnFirstInput() {
        // Get the input element with the id "first-input" and trigger a click event on it
        var firstInput = document.getElementById('first-input');
        if (firstInput) {
            firstInput.click();
        }
    }

    // Call the function to focus on the first input element
    focusOnFirstInput();

    // Check if input elements are found before adding event listeners
    if (input) {
        input.forEach((element) => {
        element.addEventListener("keyup", (e) => {
            e.target.value = e.target.value.replace(/[^0-9]/g, "");
            let { value } = e.target;
            if (value.length == 1) {
            updateInputConfig(e.target, true);
            if (inputCount <= 3 && e.key != "Backspace") {
                finalInput += value;
                if (inputCount < 3) {
                updateInputConfig(e.target.nextElementSibling, false);
                }
            }
            inputCount += 1;
            } else if (value.length == 0 && e.key == "Backspace") {
                finalInput = finalInput.substring(0, finalInput.length - 1);
                if (inputCount == 0) {
                    updateInputConfig(e.target, false);
                    return false;
                }
                updateInputConfig(e.target, true);
                e.target.previousElementSibling.value = "";
                updateInputConfig(e.target.previousElementSibling, false);
                inputCount -= 1;
            } else if (value.length > 1) {
                e.target.value = value.split("")[0];
            }
            submitButton.classList.add("hide");
        });
    });
    }

    //end auto



    window.addEventListener("keyup", (e) => {
    if (inputCount > 3) {
        submitButton.classList.remove("hide");
        submitButton.classList.add("show");
        if (e.key == "Backspace") {
        finalInput = finalInput.substring(0, finalInput.length - 1);
        updateInputConfig(inputField.lastElementChild, false);
        inputField.lastElementChild.value = "";
        inputCount -= 1;
        submitButton.classList.add("hide");
        }
    }
    });

    const validateOTP = () => {
    alert("Success");
    };

    //Start
    const startInput = () => {
    inputCount = 0;
    finalInput = "";
    input.forEach((element) => {
        element.value = "";
    });
    //   updateInputConfig(inputField.firstElementChild, false);
    if (inputField) {
        inputField.firstElementChild.focus();
    }
    };

    window.onload = startInput;

    // Function to handle submit button click
    if (submitButton) {
        submitButton.addEventListener("click", () => {
        focusOnFirstInput();
        document.getElementById('first-input').focus(); // Focus on the submit button after clicking it
        });
    }

    // end custom style code
</script>